#!/usr/bin/env python

import sys
from PyQt4.QtWebKit import QWebView
from PyQt4.QtGui import QApplication
from PyQt4.QtCore import QUrl

app = QApplication(sys.argv)

browser = QWebView()
browser.setGeometry(300,100,500,600)
browser.setWindowTitle("Cyberoam Captive Portal")
browser.load(QUrl('http://192.168.5.254:8090/httpclient.html'))
browser.show()

app.exec_()
